import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/nav/NavBar";
import ToasterProvider from "@/app/providers/ToasterProvider";
import { getCurrentUser } from "@/app/actions/authActions";
import SignalRProvider from "@/app/providers/SignalRProvider";

export const metadata: Metadata = {
  title: "Literature Auctions",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <NavBar/>
        <main className="container mx-auto px-5 pt-10">
          <SignalRProvider user={user}>
            {children}
          </SignalRProvider>
        </main>
      </body>
    </html>
  );
}
